[book]
authors = ["josepmdc"]
language = "en"
multilingual = false
src = "src"
title = "notes"

[build]
build-dir = "docs"

[output.html]
no-section-label = true

[output.html.search]
enable = true
limit-results = 30
